---
- name: test stuff2
  hosts: localhost
  gather_facts: false
  connection: smart
  tasks:
    - name: touch it
      raw: "touch /tmp/helo"
    - name: signal
      raw: "cfn-signal -e0 {{ lookup('env', 'WAITHANDLE') }}"
...