---
- name: boostrap new box
  hosts: localhost
  gather_facts: false
  connection: smart
  tasks:
    - name: upgrade all packages
      yum: name=* state=latest
    - name: signal
      raw: "/opt/aws/bin/cfn-signal -e0 '{{ lookup('env', 'WAITHANDLE') }}'"
...