---
- name: boostrap new box
  hosts: localhost
  gather_facts: false
  connection: smart
  tasks:
    - name: upgrade all packages
      yum:
        name: "*"
        state: latest
    - name: download webby
      get_url:
        url: https://github.com/rendicott/dcert/releases/download/webby-v0.1/webby
        dest: /tmp
        mode: 0777
    - name: download service config
      get_url:
        url: https://raw.githubusercontent.com/rendicott/dcert/master/webby/webby.initd
        dest: /etc/init.d/webby
        mode: 0755
    - name: Add the user 'webby'
      user:
        name: webby 
        comment: webby service user
    - name: Enable webby service
      service:
        name: webby 
        enabled: yes
        state: started
...